# Locate GLOW
# This module defines
# GLOW_LIBRARIES
# GLOW_FOUND, if false, do not try to link to GLOW
# GLOW_INCLUDE_DIR, where to find the headers

FIND_PATH( GLOW_INCLUDE_DIR 
	NAMES
		glow/glow.h
	HINTS
		$ENV{GLOW_HOME}
		${GLOW_HOME}
	PATH_SUFFIXES include
	PATHS
		$ENV{GLOW_HOME}
)

FIND_LIBRARY( GLOW_LIBRARY 
	NAMES 
	glow 
	PATHS
	$ENV{GLOW_HOME}/lib
	${GLOW_HOME}/lib
)

FIND_LIBRARY( GLOW_UTILS_LIBRARY 
	NAMES 
	glowutils
	PATHS
	$ENV{GLOW_HOME}/lib
	${GLOW_HOME}/lib
)

FIND_LIBRARY( GLOW_WINDOW_LIBRARY 
	NAMES 
	glowwindow
	PATHS
	$ENV{GLOW_HOME}/lib
	${GLOW_HOME}/lib
)

FIND_LIBRARY( GLOW_LIBRARY_DEBUG
	NAMES 
	glowd 
	PATHS
	$ENV{GLOW_HOME}/lib
	${GLOW_HOME}/lib
)

FIND_LIBRARY( GLOW_UTILS_LIBRARY_DEBUG 
	NAMES 
	glowutilsd
	PATHS
	$ENV{GLOW_HOME}/lib
	${GLOW_HOME}/lib
)

FIND_LIBRARY( GLOW_WINDOW_LIBRARY_DEBUG 
	NAMES 
	glowwindowd
	PATHS
	$ENV{GLOW_HOME}/lib
	${GLOW_HOME}/lib
)

SET( GLOW_FOUND FALSE )

SET(GLOW_LIBRARIES ${GLOW_LIBRARY} ${GLOW_UTILS_LIBRARY} ${GLOW_WINDOW_LIBRARY})
SET(GLOW_LIBRARIES_DEBUG ${GLOW_LIBRARY_DEBUG} ${GLOW_UTILS_LIBRARY_DEBUG} ${GLOW_WINDOW_LIBRARY_DEBUG})

IF(GLOW_LIBRARIES AND GLOW_INCLUDE_DIR)
	SET(GLOW_FOUND TRUE)
	MESSAGE(STATUS "GLOW libraries found: ${GLOW_LIBRARIES}")
	MESSAGE(STATUS "GLOW include dir found: ${GLOW_INCLUDE_DIR}")
	IF(NOT GLOW_LIBRARIES_DEBUG)
		MESSAGE(WARNING "-- Debug GLOW not found.")
	ELSE(NOT GLOW_LIBRARIES_DEBUG)
		MESSAGE(STATUS "GLOW libraries debug found: ${GLOW_LIBRARIES_DEBUG}")
		SET(GLOW_LIBRARIES debug ${GLOW_LIBRARIES_DEBUG} optimized ${GLOW_LIBRARIES})
	ENDIF(NOT GLOW_LIBRARIES_DEBUG)
ELSE()
    message(WARNING "Note: Environment variable GLOW_HOME assists this script to locate glow")
ENDIF(GLOW_LIBRARIES AND GLOW_INCLUDE_DIR)