#  LIBPNG_FOUND
#  LIBPNG_INCLUDE_DIR 
#  LIBPNG_LIBRARY	

find_path(	LIBPNG_INCLUDE_DIR
	NAMES 
		png.h
	HINTS
		$ENV{LIBPNG_HOME}
		${LIBPNG_INCLUDE_DIR}
		${NSCP_INCLUDEDIR}
	PATH_SUFFIXES 
		include		
)

find_library( LIBPNG_LIBRARY 
	NAMES 
		libpng
		libpngd
	PATHS
		$ENV{LIBPNG_HOME}/lib
)


if(LIBPNG_LIBRARY AND LIBPNG_INCLUDE_DIR)
	set(LIBPNG_FOUND TRUE)
else(LIBPNG_LIBRARY AND LIBPNG_INCLUDE_DIR)
	set(LIBPNG_FOUND FALSE)
	message(WARNING "Note: Environment variable LIBPNG_HOME assists this script to locate LIBPNG")
endif(LIBPNG_LIBRARY AND LIBPNG_INCLUDE_DIR)

mark_as_advanced(LIBPNG_INCLUDE_DIR)